### ISSUE TITLE
Не запускается jar файл

### ISSUE THREAD

**Issue by YuliyaGer** [YuliyaGer/Docker#1]
Работаю в play with Docker, Windows 7
1. Клонировала репозиторий
2. Подгрузила java
3. Запустила Docker-compose up -d, запустился
4. Запускаю jar файл, получаю такую ошибку.

![image](https://user-images.githubusercontent.com/56927385/71778176-7665e300-2fbb-11ea-8032-f0d15f1e7c14.png)

**Comment by supremko** [comment]
Покажи еще application.properties и docker-compose.yml, пожалуйста. У тебя ошибка в том, что "База данных 'db' не существует".
